apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: controller-manager
    app.kubernetes.io/instance: tidb-operator
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: tidb-operator
    helm.sh/chart: tidb-operator-dev
  name: tidb-controller-manager
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: scheduler
    app.kubernetes.io/instance: tidb-operator
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: tidb-operator
    helm.sh/chart: tidb-operator-dev
  name: tidb-scheduler
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: controller-manager
    app.kubernetes.io/instance: tidb-operator
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: tidb-operator
    helm.sh/chart: tidb-operator-dev
  name: tidb-operator:tidb-controller-manager
rules:
- apiGroups:
  - ""
  resources:
  - services
  - events
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - create
  - get
  - update
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - update
  - delete
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - pingcap.com
  resources:
  - tidbclusters
  - tidbclusters/finalizers
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: scheduler
    app.kubernetes.io/instance: tidb-operator
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: tidb-operator
    helm.sh/chart: tidb-operator-dev
  name: tidb-operator:tidb-scheduler
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - configmaps
  - replicationcontrollers
  - persistentvolumeclaims
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/binding
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - endpoints
  - events
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  - extensions
  resources:
  - replicasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - pingcap.com
  resources:
  - tidbclusters
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - update
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: controller-manager
    app.kubernetes.io/instance: tidb-operator
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: tidb-operator
    helm.sh/chart: tidb-operator-dev
  name: tidb-operator:tidb-controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tidb-operator:tidb-controller-manager
subjects:
- kind: ServiceAccount
  name: tidb-controller-manager
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: scheduler
    app.kubernetes.io/instance: tidb-operator
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: tidb-operator
    helm.sh/chart: tidb-operator-dev
  name: tidb-operator:tidb-scheduler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tidb-operator:tidb-scheduler
subjects:
- kind: ServiceAccount
  name: tidb-scheduler
  namespace: default
---
apiVersion: v1
data:
  policy.cfg: |-
    {
      "kind" : "Policy",
      "apiVersion" : "v1",
      "predicates": [
        {"name": "NoVolumeZoneConflict"},
        {"name": "MaxEBSVolumeCount"},
        {"name": "MaxAzureDiskVolumeCount"},
        {"name": "NoDiskConflict"},
        {"name": "GeneralPredicates"},
        {"name": "PodToleratesNodeTaints"},
        {"name": "CheckVolumeBinding"},
        {"name": "MaxGCEPDVolumeCount"},
        {"name": "MatchInterPodAffinity"},
        {"name": "CheckNodeCondition"},
        {"name": "CheckNodeMemoryPressure"},
        {"name": "CheckNodeDiskPressure"},
        {"name": "CheckVolumeBinding"}
      ],
      "priorities": [
        {"name": "SelectorSpreadPriority", "weight": 1},
        {"name": "InterPodAffinityPriority", "weight": 1},
        {"name": "LeastRequestedPriority", "weight": 1},
        {"name": "BalancedResourceAllocation", "weight": 1},
        {"name": "NodePreferAvoidPodsPriority", "weight": 1},
        {"name": "NodeAffinityPriority", "weight": 1},
        {"name": "TaintTolerationPriority", "weight": 1}
      ],
      "extenders": [
        {
          "urlPrefix": "http://127.0.0.1:10262/scheduler",
          "filterVerb": "filter",
          "weight": 1,
          "httpTimeout": 30000000000,
          "enableHttps": false
        }
      ]
    }
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: scheduler
    app.kubernetes.io/instance: tidb-operator
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: tidb-operator
    helm.sh/chart: tidb-operator-dev
  name: tidb-scheduler-policy
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: controller-manager
    app.kubernetes.io/instance: tidb-operator
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: tidb-operator
    helm.sh/chart: tidb-operator-dev
  name: tidb-controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: controller-manager
      app.kubernetes.io/instance: tidb-operator
      app.kubernetes.io/name: tidb-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/component: controller-manager
        app.kubernetes.io/instance: tidb-operator
        app.kubernetes.io/name: tidb-operator
    spec:
      containers:
      - command:
        - /usr/local/bin/tidb-controller-manager
        - -default-storage-class-name=local-storage
        - -cluster-scoped=true
        - -auto-failover=false
        - -pd-failover-period=5m
        - -tikv-failover-period=5m
        - -tidb-failover-period=5m
        - -v=2
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: TZ
          value: UTC
        image: pingcap/tidb-operator:v1.0.0-beta.3
        imagePullPolicy: IfNotPresent
        name: tidb-operator
        resources:
          limits:
            cpu: 250m
            memory: 150Mi
          requests:
            cpu: 80m
            memory: 50Mi
      serviceAccount: tidb-controller-manager
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: scheduler
    app.kubernetes.io/instance: tidb-operator
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: tidb-operator
    helm.sh/chart: tidb-operator-dev
  name: tidb-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: scheduler
      app.kubernetes.io/instance: tidb-operator
      app.kubernetes.io/name: tidb-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/component: scheduler
        app.kubernetes.io/instance: tidb-operator
        app.kubernetes.io/name: tidb-operator
    spec:
      containers:
      - command:
        - /usr/local/bin/tidb-scheduler
        - -v=2
        - -port=10262
        image: pingcap/tidb-operator:v1.0.0-beta.3
        imagePullPolicy: IfNotPresent
        name: tidb-scheduler
        resources:
          limits:
            cpu: 250m
            memory: 150Mi
          requests:
            cpu: 80m
            memory: 50Mi
      - command:
        - kube-scheduler
        - --port=10261
        - --leader-elect=true
        - --lock-object-name=tidb-scheduler
        - --lock-object-namespace=default
        - --scheduler-name=tidb-scheduler
        - --v=2
        - --policy-configmap=tidb-scheduler-policy
        - --policy-configmap-namespace=default
        image: gcr.io/google-containers/hyperkube:v1.9.0
        imagePullPolicy: IfNotPresent
        name: kube-scheduler
        resources:
          limits:
            cpu: 250m
            memory: 150Mi
          requests:
            cpu: 80m
            memory: 50Mi
      serviceAccount: tidb-scheduler
