apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: local-volume-provisioner
  name: local-volume-provisioner
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: local-volume-provisioner
  template:
    metadata:
      labels:
        app: local-volume-provisioner
    spec:
      containers:
      - env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: JOB_CONTAINER_IMAGE
          value: quay.io/external_storage/local-volume-provisioner:v2.2.0
        image: quay.io/external_storage/local-volume-provisioner:v2.2.0
        name: provisioner
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /etc/provisioner/config
          name: provisioner-config
          readOnly: true
        - mountPath: /mnt/disks
          mountPropagation: HostToContainer
          name: local-disks
      serviceAccountName: local-storage-admin
      volumes:
      - configMap:
          name: local-provisioner-config
        name: provisioner-config
      - hostPath:
          path: /mnt/disks
        name: local-disks
