apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: controller-manager
    app.kubernetes.io/instance: tidb-operator
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: tidb-operator
    helm.sh/chart: tidb-operator-dev
  name: tidb-controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: controller-manager
      app.kubernetes.io/instance: tidb-operator
      app.kubernetes.io/name: tidb-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/component: controller-manager
        app.kubernetes.io/instance: tidb-operator
        app.kubernetes.io/name: tidb-operator
    spec:
      containers:
      - command:
        - /usr/local/bin/tidb-controller-manager
        - -default-storage-class-name=local-storage
        - -cluster-scoped=true
        - -auto-failover=false
        - -pd-failover-period=5m
        - -tikv-failover-period=5m
        - -tidb-failover-period=5m
        - -v=2
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: TZ
          value: UTC
        image: pingcap/tidb-operator:v1.0.0-beta.2
        imagePullPolicy: IfNotPresent
        name: tidb-operator
        resources:
          limits:
            cpu: 250m
            memory: 150Mi
          requests:
            cpu: 80m
            memory: 50Mi
      serviceAccount: tidb-controller-manager
