apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: scheduler
    app.kubernetes.io/instance: tidb-operator
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: tidb-operator
    helm.sh/chart: tidb-operator-dev
  name: tidb-scheduler
